### ISSUE TITLE
Documentation or examples for arduino uno?

### ISSUE THREAD

**Issue by ijkeleher** [vortex314/mqtt2serial#1]
Is there any documentation for using this? Sorry for the noob question but this might be perfect for a solution I'm building where I want to send messages from an arduino connected via serial to a pi acting as a MQTT broker and vice versa back again from pi to arduino.

**Comment by vortex314** [comment]
Hi inci90, there is the READM.md , the quickest setup is download the binary, configure serial2mqtt.json and there you go. 
There is also : https://vortex314.github.io/serial2mqtt.html
At the beginning of the readmemd, you find the most simple example I could come up with on Arduino side.
https://github.com/vortex314/mqtt2serial/blob/master/simple/src/main.cpp
What are you looking for ? 
Lieven

**Comment by vortex314** [comment]
Oops, I sudenly realize, this is not serial2mqtt but mqtt2serial. 
The code still uses microAkka, I've evolved since to nanoAkka so some of them are broken.
I'll spend some time on providing examples & doc. Sorry for the confusion. 
2 samples are working : simple ( all Arduino's )  and lm4f120 ( nanoAkka based )

**Comment by vortex314** [comment]
I've updated the README.md. Most of the samples should compile and work.
As there is now some documentation, I consider issue closed. Let me know if it's clear enough.

**Comment by ijkeleher** [comment]
Thanks @vortex314
